# Generated by Django 4.1 on 2022-11-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='', max_length=300)),
                ('productType', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=10000)),
                ('price', models.IntegerField(default='1')),
                ('productImage', models.ImageField(default='', upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('email', models.CharField(default='', max_length=300)),
                ('username', models.CharField(default='', max_length=300)),
                ('password', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
