# Generated by Django 4.1 on 2022-11-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('email', models.CharField(default='', max_length=300)),
                ('username', models.CharField(default='', max_length=300)),
                ('password', models.CharField(default='', max_length=300)),
                ('payment', models.FloatField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerID', models.IntegerField(default='1')),
                ('name', models.CharField(default='', max_length=300)),
                ('date', models.DateField(default='')),
                ('address', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryID', models.IntegerField(default='1')),
                ('cardNumber', models.CharField(default='', max_length=300)),
                ('amount', models.FloatField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('email', models.CharField(default='', max_length=300)),
                ('username', models.CharField(default='', max_length=300)),
                ('password', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
