# Generated by Django 4.1 on 2022-11-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_buyer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='itemsJson',
            field=models.CharField(default='', max_length=300),
        ),
    ]
