# Generated by Django 4.1 on 2022-11-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_buyer_itemsjson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('deliveryID', models.AutoField(primary_key=True, serialize=False)),
                ('buyerID', models.IntegerField(default='1')),
                ('name', models.CharField(default='', max_length=300)),
                ('date', models.DateField(default='')),
                ('address', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryID', models.IntegerField(default='1')),
                ('cardNumber', models.CharField(default='', max_length=300)),
                ('amount', models.FloatField(default='1')),
            ],
        ),
    ]
